import { apiClient, createInvalidResponseError, type ApiResponse, type JsonValue } from "../../../api";
import { isDocumentId } from "../types";
import type { HybridSearchInput, HybridSearchItem, HybridSearchResponse } from "../types";

const HYBRID_SEARCH_PATH = "/api/search/hybrid";
function requireData<T>(response: ApiResponse<T>, expectedStatus: number): T { if (response.status !== expectedStatus || response.data === null) throw createInvalidResponseError(); return response.data; }
function integer(value: unknown, minimum: number): number { if (typeof value !== "number" || !Number.isInteger(value) || value < minimum) throw createInvalidResponseError(); return value; }
function nullableRank(value: unknown): number | null { return value === null ? null : integer(value, 1); }
function parseItem(value: unknown): HybridSearchItem { if (typeof value !== "object" || value === null || Array.isArray(value)) throw createInvalidResponseError(); const item = value as Record<string, unknown>; if (!isDocumentId(item.chunk_id) || !isDocumentId(item.document_id) || typeof item.document_name !== "string" || !item.document_name.trim() || typeof item.document_type !== "string" || typeof item.knowledge_layer !== "string" || typeof item.snippet !== "string" || typeof item.hybrid_score !== "number" || !Number.isFinite(item.hybrid_score)) throw createInvalidResponseError(); return { chunkId: item.chunk_id, documentId: item.document_id, documentName: item.document_name, documentType: item.document_type as HybridSearchItem["documentType"], knowledgeLayer: item.knowledge_layer as HybridSearchItem["knowledgeLayer"], chunkIndex: integer(item.chunk_index, 1), startPage: integer(item.start_page, 1), endPage: integer(item.end_page, 1), snippet: item.snippet, hybridScore: item.hybrid_score, textRank: nullableRank(item.text_rank), semanticRank: nullableRank(item.semantic_rank) }; }
function parseResponse(value: unknown): HybridSearchResponse { if (typeof value !== "object" || value === null || Array.isArray(value)) throw createInvalidResponseError(); const response = value as Record<string, unknown>; if (!Array.isArray(response.items)) throw createInvalidResponseError(); const items = response.items.map(parseItem); const returned = integer(response.returned, 0); const topK = integer(response.top_k, 1); if (returned !== items.length || returned > topK || new Set(items.map((item) => item.chunkId)).size !== items.length) throw createInvalidResponseError(); return { items, returned, topK }; }
export async function searchHybrid(input: HybridSearchInput, signal?: AbortSignal): Promise<HybridSearchResponse> { const body: Record<string, JsonValue> = { query: input.query, text_match_mode: input.textMatchMode, top_k: input.topK }; if (input.documentId) body.document_id = input.documentId; if (input.documentTypes) body.document_types = input.documentTypes; if (input.knowledgeLayers) body.knowledge_layers = input.knowledgeLayers; if (input.minPage) body.min_page = input.minPage; if (input.maxPage) body.max_page = input.maxPage; return requireData(await apiClient.post(HYBRID_SEARCH_PATH, body, parseResponse, { signal }), 200); }
