import { apiClient, createInvalidResponseError, type ApiResponse } from "../../../api";

export interface EmbeddingStatus { readonly state: "unloaded" | "loading" | "loaded" | "error"; readonly localFilesAvailable: boolean; readonly device: string; readonly dimension: number | null; readonly automaticallyLoaded: boolean; }
export interface SemanticStatus { readonly state: "not_ready" | "ready" | "building" | "error" | "unavailable"; readonly indexedChunks: number; readonly activeChunks: number; readonly needsRebuild: boolean; readonly errorCode: string | null; }
export interface SemanticRebuild { readonly indexedChunks: number; readonly dimension: number; }
export const semanticIndexKeys = { all: ["semantic-index"] as const, model: ["semantic-index", "model"] as const, status: ["semantic-index", "status"] as const };
function data<T>(response: ApiResponse<T>, status: number): T { if (response.status !== status || response.data === null) throw createInvalidResponseError(); return response.data; }
function record(value: unknown): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw createInvalidResponseError(); return value as Record<string, unknown>; }
function embedding(value: unknown): EmbeddingStatus { const item = record(value); const dimension = item.dimension; if (!["unloaded", "loading", "loaded", "error"].includes(String(item.state)) || typeof item.local_files_available !== "boolean" || typeof item.device !== "string" || (dimension !== null && (typeof dimension !== "number" || !Number.isInteger(dimension) || dimension <= 0)) || (item.automatically_loaded !== undefined && typeof item.automatically_loaded !== "boolean")) throw createInvalidResponseError(); return { state: item.state as EmbeddingStatus["state"], localFilesAvailable: item.local_files_available, device: item.device, dimension: dimension as number | null, automaticallyLoaded: item.automatically_loaded === true }; }
function semantic(value: unknown): SemanticStatus { const item = record(value); if (! ["not_ready", "ready", "building", "error", "unavailable"].includes(String(item.state)) || !Number.isInteger(item.indexed_chunks) || !Number.isInteger(item.active_chunks) || typeof item.needs_rebuild !== "boolean" || (item.error_code !== null && typeof item.error_code !== "string")) throw createInvalidResponseError(); return { state: item.state as SemanticStatus["state"], indexedChunks: item.indexed_chunks as number, activeChunks: item.active_chunks as number, needsRebuild: item.needs_rebuild, errorCode: item.error_code as string | null }; }
function rebuild(value: unknown): SemanticRebuild { const item = record(value); if (item.state !== "ready" || !Number.isInteger(item.indexed_chunks) || !Number.isInteger(item.embedding_dimension)) throw createInvalidResponseError(); return { indexedChunks: item.indexed_chunks as number, dimension: item.embedding_dimension as number }; }
export async function getEmbeddingStatus(signal?: AbortSignal) { return data(await apiClient.get("/api/models/embeddings/status", embedding, { signal }), 200); }
export async function loadEmbeddings() { return data(await apiClient.post("/api/models/embeddings/load", {}, embedding), 200); }
export async function unloadEmbeddings() { return data(await apiClient.post("/api/models/embeddings/unload", {}, embedding), 200); }
export async function getSemanticStatus(signal?: AbortSignal) { return data(await apiClient.get("/api/search/semantic/status", semantic, { signal }), 200); }
export async function rebuildSemanticIndex() { return data(await apiClient.post("/api/search/semantic/rebuild", {}, rebuild), 200); }
